# IS 4487 Lab 3

## Outline

Repeat exercises from Lab 2, but with the *SuperStore Retail Orders* dataset
- Loading installed packages
- Inspect data
- Explore plot types

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/Scripts/lab_03_retailer_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Superstore Data Dictionary

 ORDER VARIABLES:
 - Order ID
 - Order Date
 - Order Year Month - Year and month of the order
 - Order Type - Was the order completed at a store or online? (Retail, Online)
 - Quantity - Quantity ordered for the product

 CUSTOMER VARIABLES:
 - Customer Name
 - City
 - State Province
 - Email

PRODUCT VARIABLES:
 - Product Name
 - Product Line - Category of the product (i.e. Bikes Phones)
 - Product Price - Price in US Dollars
 - Product Status - Current status of the product (Active, Inactive)

## Load Libraries

➡️ Assignment Tasks
- Load any necessary libraries

In [1]:
#Importing libraries
import pandas as pd
import numpy as np

## Import Data into Dataframe

➡️ Assignment Tasks
- Import data from the SuperStore retail dataset into a dataframe (in GitHub go to Labs > DataSets)
- Describe or profile the dataframe

In [2]:
#Importing the data into database
df = pd.read_csv('https://github.com/Stan-Pugsley/is_4487_base/blob/main/Labs/DataSets/superstore_retail_orders.csv?raw=true')
print (df)

       order_id  order_date order_year_month     customer_name  \
0         51188  2023-07-01          2023-07     Audrey Blanco
1         51187  2023-07-01          2023-07       Isaac Allen
2         51199  2023-07-02          2023-07        Ian Morgan
3         51241  2023-07-04          2023-07        Alexa Bell
4         51297  2023-07-08          2023-07        Casey Diaz
...         ...         ...              ...               ...
56038     74084  2024-06-29          2024-06        Ian Rogers
56039     74062  2024-06-29          2024-06   Marcus Anderson
56040     74065  2024-06-29          2024-06  Nathaniel Howard
56041     74038  2024-06-29          2024-06        Robin Sanz
56042     74110  2024-06-30          2024-06   Mallory Jimenez

                    city state_province                       email  \
0      North Cherylmouth  New Hampshire     audrey_blanco@email.com
1             Traceyland  West Virginia       isaac_allen@email.com
2              Dylanberg   South Dakota        ian_morgan@email.com
3         Lake Tracytown      Wisconsin        alexa_bell@email.com
4            Byrdchester    Mississippi        casey_diaz@email.com
...                  ...            ...                         ...
56038          Port Mark        Alabama        ian_rogers@email.com
56039     West Aprilfurt       Nebraska   marcus_anderson@email.com
56040      New Lindaview       Illinois  nathaniel_howard@email.com
56041    West Frankhaven       Arkansas        robin_sanz@email.com
56042        Dillonhaven       Maryland   mallory_jimenez@email.com

      order_type  quantity                                       product_name  \
0         Retail       3.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
1         Online       4.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
2         Online       5.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
3         Online       1.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
4         Online       1.0  Apple iPhone XR (Yellow, 256 GB) (Includes Ear...
...          ...       ...                                                ...
56038     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56039     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56040     Online       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56041     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...
56042     Retail       1.0  Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...

      product_line  product_price product_status
0           Mobile         649.99         Active
1           Mobile         649.99         Active
2           Mobile         649.99         Active
3           Mobile         649.99         Active
4           Mobile         649.99         Active
...            ...            ...            ...
56038  Electronics         914.62         Active
56039  Electronics         914.62         Active
56040  Electronics         914.62         Active
56041  Electronics         914.62         Active
56042  Electronics         914.62         Active

[56043 rows x 13 columns]

In [3]:
#look at the top rows
df.head(10)

,order_id,order_date,order_year_month,customer_name,city,state_province,email,order_type,quantity,product_name,product_line,product_price,product_status
0,51188,2023-07-01,2023-07,Audrey Blanco,North Cherylmouth,New Hampshire,audrey_blanco@email.com,Retail,3.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
1,51187,2023-07-01,2023-07,Isaac Allen,Traceyland,West Virginia,isaac_allen@email.com,Online,4.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
2,51199,2023-07-02,2023-07,Ian Morgan,Dylanberg,South Dakota,ian_morgan@email.com,Online,5.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
3,51241,2023-07-04,2023-07,Alexa Bell,Lake Tracytown,Wisconsin,alexa_bell@email.com,Online,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
4,51297,2023-07-08,2023-07,Casey Diaz,Byrdchester,Mississippi,casey_diaz@email.com,Online,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
5,51319,2023-07-09,2023-07,Troy Rodriguez,South Brendamouth,Ohio,troy_rodriguez@email.com,Online,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
6,51357,2023-07-11,2023-07,Natalie Phillips,Rachelburgh,Alabama,natalie_phillips@email.com,Online,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
7,51371,2023-07-12,2023-07,Dalton Mitchell,Michaeltown,Virginia,dalton_mitchell@email.com,Online,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
8,51424,2023-07-15,2023-07,Timothy James,West Pamela,New York,timothy_james@email.com,Retail,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active
9,51452,2023-07-17,2023-07,Fernando Scott,East Maureenbury,South Dakota,fernando_scott@email.com,Retail,1.0,"Apple iPhone XR (Yellow, 256 GB) (Includes Ear...",Mobile,649.99,Active

In [4]:
#look at last rows
df.tail(10)

,order_id,order_date,order_year_month,customer_name,city,state_province,email,order_type,quantity,product_name,product_line,product_price,product_status
56033,74083,2024-06-29,2024-06,Alex Murphy,South William,Missouri,alex_murphy@email.com,Online,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56034,74032,2024-06-29,2024-06,Ashlee Tang,Lake Robin,Hawaii,ashlee_tang@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56035,74063,2024-06-29,2024-06,Carmen Raman,Bellshire,Nevada,carmen_raman@email.com,Online,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56036,74074,2024-06-29,2024-06,Carol Xu,Erichaven,New Hampshire,carol_xu@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56037,74055,NaN,NaN,Francis Ortega,Port Cynthiatown,Washington,francis_ortega@email.com,Online,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56038,74084,2024-06-29,2024-06,Ian Rogers,Port Mark,Alabama,ian_rogers@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56039,74062,2024-06-29,2024-06,Marcus Anderson,West Aprilfurt,Nebraska,marcus_anderson@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56040,74065,2024-06-29,2024-06,Nathaniel Howard,New Lindaview,Illinois,nathaniel_howard@email.com,Online,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56041,74038,2024-06-29,2024-06,Robin Sanz,West Frankhaven,Arkansas,robin_sanz@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active
56042,74110,2024-06-30,2024-06,Mallory Jimenez,Dillonhaven,Maryland,mallory_jimenez@email.com,Retail,1.0,"Samsung Galaxy S20 FE 5G (Cloud Navy, 8GB RAM,...",Electronics,914.62,Active

In [5]:
#get a summary of the dataset
df.describe()

           order_id       quantity  product_price
count  56043.000000   56004.000000   56043.000000
mean   61668.410578       3.348582    6198.309433
std     7508.142486     422.654112   35784.965255
min    45079.000000       1.000000       2.290000
25%    55644.500000       1.000000       7.950000
50%    61870.000000       1.000000     475.600000
75%    68097.000000       2.000000     914.620000
max    74147.000000  100000.000000  235481.000000

In [6]:
#look at the datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56043 entries, 0 to 56042
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          56043 non-null  int64
 1   order_date        56011 non-null  object
 2   order_year_month  56011 non-null  object
 3   customer_name     56043 non-null  object
 4   city              55569 non-null  object
 5   state_province    55569 non-null  object
 6   email             56043 non-null  object
 7   order_type        56043 non-null  object
 8   quantity          56004 non-null  float64
 9   product_name      56043 non-null  object
 10  product_line      56043 non-null  object
 11  product_price     56043 non-null  float64
 12  product_status    56043 non-null  object
dtypes: float64(2), int64(1), object(10)
memory usage: 5.6+ MB

## Prepare Data

➡️ Assignment Tasks
- Create a "revenue" variable and make sure it is a numeric datatype
- Remove rows with empty (NULL) values
- Locate outliers in at least two of the variables.   Filter them out if they are mistakes; keep them if they are exceptional cases.

In [7]:
#Creates a "revenue" variable and makes sure it is a numeric datatype
df['revenue'] = df['quantity'] * df['product_price']
df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')

In [8]:
#Removes rows with empty (NULL) values
df.dropna(inplace=True)

In [9]:
# Example for 'quantity' and 'product_price' columns
for column in ['quantity', 'product_price']:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Identify outliers
    outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]

    # Print some info about the outliers
    print(f"Outliers in {column}:")
    print(outliers[[column, 'revenue']])

    # Decision making and filtering (example logic)
    if column == 'quantity' and any(outliers['quantity'] < 0):
        df = df[(df['quantity'] >= lower_bound) & (df['quantity'] <= upper_bound)]
    elif column == 'product_price' and any(outliers['product_price'] > 1000):
        df = df[(df['product_price'] >= lower_bound) & (df['product_price'] <= upper_bound)]
    else:
        pass

Outliers in quantity:
       quantity     revenue
1           4.0     2599.96
2           5.0     3249.95
33727     200.0      998.00
33822  100000.0   499000.00
44626     600.0  2024994.00
45530     100.0   357827.00
45752      20.0    71565.40
45857     500.0  1789135.00
55308    2000.0  1829240.00
Outliers in product_price:
       product_price  revenue
1342         2498.00  2498.00
1343         2498.00  2498.00
1344         2498.00  2498.00
1345         2498.00  2498.00
1346         2498.00  2498.00
...              ...      ...
46337        3578.27  3578.27
46338        3578.27  3578.27
46339        3578.27  3578.27
46340        3578.27  3578.27
46341        3578.27  3578.27

[4044 rows x 2 columns]

## Summarize Data

➡️ Assignment Tasks
- Display the average price per product line
- Display the total revenue for all months

In [10]:
#average price
average_price_per_product_line = df.groupby('product_line')['product_price'].mean()
print(average_price_per_product_line)

product_line
Accessories         11.531647
Bikes             1694.092466
Cameras            733.843016
Clothing            51.257239
Electronics        693.973186
Mobile            1013.581162
OfficeProducts       8.640000
Name: product_price, dtype: float64

In [11]:
#total revenue
total_revenue_per_month = df.groupby('order_year_month')['revenue'].sum()
print(total_revenue_per_month)

order_year_month
1922-06      30559.79
2022-01      16079.30
2022-02      13282.90
2022-03      13982.00
2022-04      16778.40
2022-05      16778.40
2022-06      19574.80
2022-07     341957.28
2022-08     389414.46
2022-09     265522.64
2022-10     328532.80
2022-11     233153.10
2022-12     490108.12
2023-01     349351.96
2023-02     366904.98
2023-03     386839.02
2023-04     429359.06
2023-05     480725.00
2023-06     449074.14
2023-07     980469.48
2023-08    1677180.30
2023-09    1736433.11
2023-10    1819621.25
2023-11    1946235.12
2023-12    2551542.14
2024-01    2124518.90
2024-02    2068918.77
2024-03    4628057.19
2024-04    2350829.40
2024-05    2710023.00
2024-06    2620694.15
2029-06         19.55
2029-07      41775.34
2029-08         39.94
2421-09      32051.29
Name: revenue, dtype: float64